Repository blockchainworkbench/workbench-ui, pull requests merged in 2019-04, with the labels that each got.

#31 First UI for homepage and eslint
  .eslintrc
  package-lock.json
  package.json
  public/assets/logo.svg
  public/index.html
  src/assets/img/block-white.png
  src/assets/img/block.png
  src/assets/img/brand-logo-white-small.png
  src/assets/img/brand-logo-white.png
  src/assets/img/undraw_deliveries_131a.svg
  src/assets/img/undraw_operating_system_4lr6.svg
  src/assets/img/worker.png
  src/assets/img/worker.svg
  src/components/App.js
  src/components/Home.js
  src/components/layout/Footer.js
  src/components/layout/Navigation.js
  src/components/layout/TitleHeader.js
  src/components/page/CodeEditor.js
  src/components/page/elements/ExerciseElement.js
  src/components/search/SearchComponent.js
  src/components/search/SearchPage.js
  src/index.css
  src/sagas/pages.js
Labels: enhancement

#32 Feature exercise testing
  package-lock.json
  package.json
  public/assets/Assert.sol
  src/actions/index.js
  src/actions/testing.js
  src/components/App.js
  src/components/layout/CategorySteps.js
  src/components/page/PageContent.js
  src/components/page/Pages.js
  src/components/page/elements/ExerciseElement.js
  src/components/search/CategoryFilter.js
  src/components/search/CategoryList.js
  src/components/search/PageList.js
  src/components/search/PageListItem.js
  src/components/testing/ExerciseTest.js
  src/components/testing/ExerciseTestInput.js
  src/components/testing/ExerciseTestPreview.js
  src/components/testing/Testing.js
  src/lib/builder.js
  src/lib/helpers.js
  src/lib/saga-action-filter.js
  src/reducers/app-state/web3-account.js
  src/reducers/index.js
  src/reducers/testing.js
  src/sagas/exercises.js
  src/sagas/index.js
  src/sagas/pages-sorted.js
  src/sagas/solidity-compiler.js
  src/sagas/testing.js
  src/sagas/web3-accounts.js
Labels: enhancement

#34 UI and refactoring
  package-lock.json
  src/assets/img/brand-logo-blue-small.png
  src/assets/img/undraw_404_error.svg
  src/components/App.js
  src/components/Home.js
  src/components/layout/CategorySteps.js
  src/components/layout/Footer.js
  src/components/layout/LoadingIndicator.js
  src/components/layout/Navigation.js
  src/components/page/CodeEditor.js
  src/components/page/Page.js
  src/components/page/Page404.js
  src/components/page/PageContent.js
  src/components/page/elements/CodeBlockElement.js
  src/components/page/elements/ExerciseElement.js
  src/index.css
Labels: enhancement

#47 Feature 404 error page
  src/assets/img/undraw_404_error.svg
  src/components/page/Page404.js
  src/components/page/Pages.js
Labels: enhancement, ui

#45 Feature navigation menu for pages
  src/components/layout/CategorySidebar.js
  src/components/layout/CategorySteps.js
  src/components/page/Page.js
  src/components/page/PageContent.js
  src/components/page/Pages.js
  src/index.css
  src/lib/helpers.js
Labels: enhancement, ui

#50 fix for landing image too big
  src/index.css
Labels: enhancement, ui

#52 :sparkles: Add partners
  src/assets/img/partners/hslu_logo.svg
  src/assets/img/partners/iO_Red.png
  src/assets/img/partners/imperial_logo.svg
  src/components/Home.js
  src/index.css
Labels: enhancement, ui

#54 :lipstick: Remove pages from category since already in sidebar
  src/components/page/Pages.js
Labels: enhancement, ui

#53 Feature searchbar
  src/components/layout/Navigation.js
  src/components/page/Pages.js
  src/components/search/CategoryFilter.js
  src/components/search/DifficultyFilter.js
  src/components/search/PageList.js
  src/components/search/PageListItem.js
  src/components/search/SearchComponent.js
  src/components/search/SearchFilter.js
  src/components/search/SearchPage.js
  src/index.css
Labels: bug, enhancement, ui
